name: Laravel CI

on:
  push:
    branches: [ "Emiliano-Danny-Francela" ]
  pull_request:
    branches: [ "Emiliano-Danny-Francela" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, sqlite, pdo_sqlite
        tools: composer:v2
        coverage: none

    - name: Copy Environment File
      run: cp .env.example .env

    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-progress --ignore-platform-reqs

    - name: Generate key
      run: php artisan key:generate

    - name: Execute tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: ":memory:"
      run: php artisan test
